import { test, expect } from '@playwright/test'
import fs from 'node:fs'

test('three languages, responsive layout and PWA icons', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'On fait une partie ?' })).toBeVisible()
  await page.screenshot({ path: '../artifacts/home-desktop.png', fullPage: true })
  await page.getByRole('combobox', { name: 'Langue', exact: true }).selectOption('mg')
  await expect(page.getByRole('heading', { name: 'Andao hilalao!' })).toBeVisible()
  await page.getByRole('combobox', { name: 'Fiteny', exact: true }).selectOption('en')
  await expect(page.getByRole('heading', { name: 'Fancy a game?' })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('combobox', { name: 'Language', exact: true }).selectOption('fr')
  await page.screenshot({ path: '../artifacts/home-mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  const svg = fs.readFileSync('public/icon.svg', 'utf8')
  for (const size of [192, 512]) {
    await page.setViewportSize({ width: size, height: size })
    await page.setContent(`<style>html,body{margin:0;padding:0;background:transparent}svg{width:100vw;height:100vh;display:block}</style>${svg}`)
    await page.screenshot({ path: `public/icon-${size}.png`, omitBackground: true })
  }
})

test('complete two-player game with private answers, voting and victory', async ({ browser }) => {
  const hostContext = await browser.newContext(), guestContext = await browser.newContext({ viewport: { width: 390, height: 844 } })
  const host = await hostContext.newPage(), guest = await guestContext.newPage()
  const errors: string[] = []
  let subscribed = false
  host.on('websocket', socket => socket.on('framereceived', frame => { if (String(frame.payload).includes('pusher_internal:subscription_succeeded')) subscribed = true }))
  host.on('pageerror', e => errors.push(e.message)); guest.on('pageerror', e => errors.push(e.message))
  await host.goto('/')
  await host.getByTestId('nickname').fill('Lova')
  await host.getByTestId('target').fill('10')
  await host.getByRole('combobox', { name: 'Temps de réponse', exact: true }).selectOption('10')
  await host.getByRole('button', { name: 'Créer ma salle' }).click()
  const code = await host.getByTestId('room-code').innerText()
  await expect.poll(() => subscribed).toBeTruthy()
  await expect(host.getByRole('button', { name: 'Lancer la partie' })).toBeDisabled()
  await guest.goto('/')
  await guest.getByRole('tab', { name: 'Rejoindre', exact: true }).click()
  await guest.getByTestId('nickname').fill('Mialy')
  await guest.getByTestId('join-code').fill(code)
  await guest.getByRole('button', { name: 'Rejoindre la partie' }).click()
  await expect(guest.getByTestId('room-code')).toHaveText(code)
  await expect(host.getByRole('button', { name: 'Lancer la partie' })).toBeEnabled()
  await host.screenshot({ path: '../artifacts/lobby.png', fullPage: true })
  await host.getByRole('button', { name: 'Lancer la partie' }).click()
  await expect(host.getByTestId('answer')).toBeEnabled()
  const letter = await host.getByTestId('letter').innerText()
  const category = await host.locator('.round-title .pill').innerText()
  await host.getByTestId('answer').fill(`${letter}ina`)
  await expect(host.getByText('Appuie sur Entrée pour enregistrer ta réponse.')).toBeVisible()
  await host.waitForTimeout(600)
  await expect(host.getByText('Réponse enregistrée', { exact: true })).toHaveCount(0)
  await host.getByTestId('answer').press('Enter')
  await expect(host.getByText('Réponse enregistrée', { exact: true })).toBeVisible()
  await expect(guest.getByTestId('answer')).toBeEnabled()
  await expect(guest.getByText(`${letter}ina`, { exact: true })).toHaveCount(0)
  await guest.getByTestId('answer').fill(`${letter}ob`)
  await guest.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(guest.getByText('Réponse enregistrée', { exact: true })).toBeVisible()
  await guest.screenshot({ path: '../artifacts/round-mobile.png', fullPage: true })
  await expect(host.getByRole('heading', { name: 'Mitsara.' })).toBeVisible({ timeout: 20000 })
  await expect(guest.getByRole('heading', { name: 'Mitsara.' })).toBeVisible()
  await expect(host.getByTestId('judging-letter')).toHaveText(letter)
  await expect(host.getByTestId('judging-category')).toHaveText(category)
  const googleCheck = host.getByRole('link', { name: `Rechercher « ${letter}ob » sur Google pour vérifier la réponse` })
  await expect(googleCheck).toHaveAttribute('target', '_blank')
  await expect(googleCheck).toHaveAttribute('href', `https://www.google.com/search?q=${encodeURIComponent(`Est-ce que « ${letter}ob » appartient à la catégorie « ${category} » ? oui ou non`)}`)
  await host.locator('#judging-comment').fill('Salama')
  await host.locator('.chat-form button').click()
  await expect(host.locator('.chat-messages').getByText('Salama')).toBeVisible()
  await expect(guest.locator('.chat-messages').getByText('Salama')).toBeVisible()
  await host.locator('#judging-comment').fill('Manao ahoana')
  await host.locator('.chat-form button').click()
  await expect(guest.locator('.chat-messages').getByText('Manao ahoana')).toBeVisible()
  await host.getByRole('button', { name: 'Incorrect', exact: true }).click()
  await guest.getByRole('button', { name: 'Valide', exact: true }).click()
  await expect(host.getByRole('button', { name: 'Afficher les résultats' })).toBeEnabled()
  await host.screenshot({ path: '../artifacts/judging.png', fullPage: true })
  await host.getByRole('button', { name: 'Afficher les résultats' }).click()
  await expect(host.getByRole('heading', { name: 'Lova remporte la partie !' })).toBeVisible()
  await expect(guest.getByRole('heading', { name: 'Lova remporte la partie !' })).toBeVisible()
  await host.reload()
  await expect(host.getByRole('heading', { name: 'Lova remporte la partie !' })).toBeVisible()
  await host.screenshot({ path: '../artifacts/victory.png', fullPage: true })
  expect(errors).toEqual([])
  await hostContext.close(); await guestContext.close()
})
